version: '3'
volumes:
  volume:
services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "pi_db"
    ports:
      - "3306:3306"
    volumes:
      - ./volume:/var/lib/mysql
    # networks:
    #   - mysql-compose-network

  # adminer:
  #   image: adminer
  #   # environment:
  #   #   DB_CONNECTION: mysql
  #   #   DB_HOST: mysqlsrv
  #   #   DB_PORT: 3306
  #   #   DB_DATABASE: "digital_house_db"
  #   #   DB_USERNAME: "admin"
  #   #   DB_PASSWORD: "admin"
  #   ports:
  #     - 8080:8080
  #   networks:
  #     - mysql-compose-network

# networks:
#   mysql-compose-network:
#     driver: bridge